blueprint:
  name: Luftfeuchtigkeits-Warnung
  description: >-
      Warnt bei erhöhter/zu hoher Luftfeuchtigkeit in einem Raum, sofern das
      Fenster geschlossen ist. Intergration --- Thermal Comfort --- inkl.
      Absoluter Luftfeuchtigkeit für draußen und den entsprechenden Raum,
      sowie ein Sensor zur jeweiligen Differenz (angelegt als
      Sensor-Template-Helfer -Diff. absolute Luftfeuchtigkeit {Raum} zu
    input:
    humidity_diff_sensor:
      name: Differenz-Feuchtigkeitssensor (absolut innen zu außen)
      selector:
        entity:
          domain: sensor
    relativ_humidity_sensor:
      name: Luftfeuchtigkeitssensor (relativ) (Raum, in %)
      selector:
        entity:
          domain: sensor
    absolute_threshold:
      name: Absolute Schwelle (in %)
      default: 59
      selector:
        number:
          min: 0
          max: 100
          step: 1
    window_sensor:
      name: Fenstersensor
      selector:
        entity:
          domain: binary_sensor
    room_name:
      name: Raumname (für die Nachricht)
      selector:
        text:
    threshold_warn:
      name: Schwelle "erhöht"
      default: 1.5
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
    for_warn:
      name: Verzögerung "erhöht" (Minuten)
      default: 5
      selector:
        number:
          min: 0
          max: 60
          step: 1
    threshold_critical:
      name: Schwelle "zu hoch"
      default: 3.5
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
    for_critical:
      name: Verzögerung "zu hoch" (Minuten)
      default: 15
      selector:
        number:
          min: 0
          max: 60
          step: 1

variables:
  room_name: !input room_name

triggers:
  - trigger: numeric_state
    entity_id: !input humidity_diff_sensor
    above: !input threshold_warn
    for:
      minutes: !input for_warn
    id: warn
  - trigger: numeric_state
    entity_id: !input humidity_diff_sensor
    above: !input threshold_critical
    for:
      minutes: !input for_critical
    id: critical

conditions:
  - condition: state
    entity_id: !input window_sensor
    state: "off"
  - condition: numeric_state
    entity_id: !input relativ_humidity_sensor
    above: !input absolute_threshold

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: warn
        sequence:
          - action: script.notify_admin
            data:
              group_admins_enable: true
              group_family_enable: false
              alexa_enabled: false
              google_enabled: false
              critical_enabled: false
              title: "Luftfeuchtigkeit {{ room_name }}"
              message: "Luftfeuchtigkeit in {{ room_name }} erhöht"
      - conditions:
          - condition: trigger
            id: critical
        sequence:
          - action: script.notify_admin
            data:
              group_admins_enable: true
              group_family_enable: false
              alexa_enabled: false
              google_enabled: false
              critical_enabled: false
              title: "Luftfeuchtigkeit {{ room_name }}"
              message: "Luftfeuchtigkeit in {{ room_name }} zu hoch. Bitte Lüften!"

mode: single
